/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#include "messageUtils.h"

enum {
    COLUMN_USER,
    COLUMN_GROUP,
    COLUMN_HOST,
    COLUMN_IP,
    COLUMN_LOGIN,
    N_COLUMNS
};

GtkWidget* create_window1 (void);

